### ISSUE TITLE
Add an option to randomly assign a reviewer from a team or list of users.

### ISSUE THREAD

**Issue by TansyArron** [pullapprove/support#111]
We're using pullapprove to help us assign reviewers conditionally. If someone modifies <file>, we need to assign a translations reviewer. 

As it stands currently, I get back a list of "review required from 1 of: <list of all our translations auditors>" Which leaves actually assigning a reviewer from the group as a manual task for the author of the pull request, and because the list is always alphabetical, I'm betting the translations auditors with names beginning with 'A' will get most of the review work.

Having an option to return only "review required from: <randomly selected member of that group>" would be great.

If #81 is in progress, an alternative might be the existing "review required from 1 of: <list of group members>" and a comment with "<group-name>: @<a randomly selected member of that group>"

**Comment by davegaeddert** [comment]
Got it. GitHub is doing some work related to "suggested reviewers" too, so we're trying to figure out how the two might work together.

**Comment by davegaeddert** [comment]
The new PullApprove v3 is completely redesigned and rebuilt on GitHub reviews and should handle this nicely. For example, you could have it randomly request a review from 1 person in the list:
```yml
version: 3
groups:
  code:
    reviews:
      required: 1
      request: 1
      request_order: random
    reviewers:
      users:
      - user1
      teams:
      - team1
      - team2
```

More info here: https://www.pullapprove.com
