### ISSUE TITLE
Condition expression error: `draft` is undefined in not draft

### ISSUE THREAD

**Issue by josephperrott** [pullapprove/support#128]
For our config, we attempted to place PRs that are in draft mode into a pending state, however it looks like it failed to read the draft value.  However, it worked as expected with `/pullapprove-test`.

In our config we had
```yaml
# turn on 'draft' support
# https://docs.pullapprove.com/config/github-api-version/
# https://developer.github.com/v3/previews/#draft-pull-requests
github_api_version: "shadow-cat-preview"

pullapprove_conditions:
  - condition: "'WIP' not in title"
    unmet_status: pending
    explanation: "Waiting to send reviews as PR is WIP"
  - condition: "'PR state: WIP' not in labels"
    unmet_status: pending
    explanation: "Waiting to send reviews as PR is WIP"
  - condition: "not draft"
    unmet_status: pending
    explanation: "Waiting to send reviews as PR is in draft"
```

![image](https://user-images.githubusercontent.com/10864441/74285649-2a553f00-4cdb-11ea-97f1-2baa898e5375.png)

Is there a way for us to properly test this will work before having to commit the `condition` again in a new PR?
