### ISSUE TITLE
Require review from at least one user from at least 2 different groups

### ISSUE THREAD

**Issue by pjurczynski** [pullapprove/support#129]
Scenario:
I have 4 groups team-A, team-B, team-C, team-D
I'm managing a monorepo with a shared space
I want to ensure that any change made to the shared space is reviewed by at least 2 teams.

My solution:
```yml
groups:
  shared-code-team-a
    conditions:
      - files.include('shared/*')
      - len(groups.approved.include('shared-code-*')) < 2
    reviewers:
      teams:
        - team-a
    reviews:
      required: 1
      request: 100

  shared-code-team-b
    conditions:
      - files.include('shared/*')
      - len(groups.approved.include('shared-code-*')) < 2
    reviewers:
      teams:
        - team-b
    reviews:
      required: 1
      request: 100

  ... (same for team-c and team-d
```

Unfortunately this doesn't work for me. I assume that `len(groups.approved.include('shared-code-*')) < 2` yields different result that I expected. (I didn't find a way to test this in an easier manner).

**Comment by davegaeddert** [comment]
Hey @pjurczynski. Yeah you're right in assuming the `groups.approved` isn't working quite like that -- groups get evaluated in order, so when you're using `groups` in conditions, it will only know about the groups that were listed before it. So "shared-code-team-a" will have 0 groups when the conditions runs, "shared-code-team-b" will have 1 group to look at ("shared-code-team-a"), and so on. Does that make sense?

This scenario is a little tricky... I think it might require one of the features that is in [discussion right now](https://github.com/dropseed/pullapprove/pull/80). The short version is that I think we're going to add a `group.type = "optional"` setting here very soon (maybe next week?). That would allow you to do something like this:
```yaml
groups:
  shared-code-team-a:
    type: optional
    conditions:
      - files.include('shared/*')
    reviewers:
      teams: [team-a]

  shared-code-team-b:
    type: optional
    conditions:
      - files.include('shared/*')
    reviewers:
      teams: [team-b]

  shared-code-team-c:
    type: optional
    conditions:
      - files.include('shared/*')
    reviewers:
      teams: [team-c]

  shared-code-team-d:
    type: optional
    conditions:
      - files.include('shared/*')
    reviewers:
      teams: [team-d]
      
  shared:
    type: required
    conditions:
      - len(groups.approved.include('shared-code-*')) >= 2
    reviews:
      required: 0
```
I'd have to test it, but I think that would work. What do you think?

The simpler alternative is something like this, but I'm guessing you've considered it and it isn't strict enough (team-a could have two people approve, for example).
```yaml
groups:
  shared:
    conditions:
      - fles.include('shared/*')
    reviews:
      required: 2
      request: 2
      request_order: random
    reviewers:
      teams:
        - team-a
        - team-b
        - team-c
        - team-d
```

**Comment by pjurczynski** [comment]
ah, that's a piece of vital information. That means:

```yml
groups:
  shared-code:
    conditions:
      - files.include('shared/*')
      - len(groups.approved.include('shared-code-*')) < 2
    reviewers:
      teams:
        - team-a
        - team-b
        - team-c
        - team-d
    reviews:
      required: 100
      request: 100

  shared-code-team-a:
    conditions:
      - files.include('shared/*')
    reviewers:
      teams:
        - team-a
    reviews:
      required: 1
      request: 1

  shared-code-team-b:
    conditions:
      - files.include('shared/*')
    reviewers:
      teams:
        - team-b
    reviews:
      required: 1
      request: 1

  ... (same for team-c and team-d
```

would work with the current set of features! I'll confirm tomorrow (it's already past my current working hours ;) ).

PS.
I think it would be worth it to include this piece of information in the docs.
