### ISSUE TITLE
Adding support for yaml anchors (aliases)

### ISSUE THREAD

**Issue by pjurczynski** [pullapprove/support#130]
Recently my rules for pullapprove are getting more and more repeatable. I would love to see support for yaml anchors (aliases). (http://blogs.perl.org/users/tinita/2019/05/reusing-data-with-yaml-anchors-aliases-and-merge-keys.html)

Usage example:

Before:
```yaml
groups:
  group-a:
    conditions:
      - "files.include('apps/a*')"
    reviewers:
      users:
        - user-a
        - user-a2
        - user-a3
    reviews:
      required: 1
      request: 1
      author_value: 0
      request_order: shuffle

  group-b:
    conditions:
      - "files.include('apps/b*')"
    reviewers:
      users:
        - user-b
        - user-b2
        - user-b3
    reviews:
      required: 1
      request: 1
      author_value: 0
      request_order: shuffle  
```

After

```yaml
defaultsReviews: &defaultReviews
  required: 1
  request: 1
  author_value: 0
  request_order: shuffle

groups:
  group-a:
    conditions:
      - "files.include('apps/a*')"
    reviewers:
      users:
        - user-a
    reviews:
      << : *defaultReviews

  group-b:
    conditions:
      - "files.include('apps/b*')"
    reviewers:
      users:
        - user-b
      << : *defaultReviews
```

Use case 2:

I can't use github teams to manage the reviewers, but with aliases I could do it in the pullapprove directly:

```yaml
securityTeam: &securityTeam
  - user-a
  - user-a2
  - user-a3

backendTeam: &backendTeam
  - user-b
  - user-b2
  - user-b3

groups:
  group-a:
    conditions:
      - "files.include('apps/a*')"
    reviewers:
      users:
        <<: *securityTeam
        <<: *backendTeam

  group-b:
    conditions:
      - "files.include('apps/b*')"
    reviewers:
      users:
        <<: *backendTeam
```

currently it fails with
```json
    "errors": [
      {
        "title": "Basic YAML parsing error",
        "description": "expected a mapping for merging, but found scalar",
        "start_line": 1,
        "start_column": 4,
        "end_line": null,
        "end_column": null
      }
    ]
```

(anchors are part of the yaml spec: https://yaml.org/spec/1.2/spec.html#id2765878)

**Comment by davegaeddert** [comment]
Two things going on here, from what I can tell.

This one would be valid but we have a strict list of field names you can use, so it probably just fails because "defaultReviews" isn't something we allow. This question is good timing too -- the suggestion I made to another customer yesterday was that we add an allowed "meta" field that you can use however you want (YAML anchors being one of those uses).

```yaml
defaultsReviews: &defaultReviews
  required: 1
  request: 1
  author_value: 0
  request_order: shuffle

groups:
  group-a:
    conditions:
      - "files.include('apps/a*')"
    reviewers:
      users:
        - user-a
    reviews:
      << : *defaultReviews

  group-b:
    conditions:
      - "files.include('apps/b*')"
    reviewers:
      users:
        - user-b
      << : *defaultReviews
```

So that may just become this and work just fine (once I add "meta", or whatever that ends up being called):
```yaml
meta:
  defaultsReviews: &defaultReviews
    required: 1
    request: 1
    author_value: 0
    request_order: shuffle

groups:
  group-a:
    conditions:
      - "files.include('apps/a*')"
    reviewers:
      users:
        - user-a
    reviews:
      << : *defaultReviews

  group-b:
    conditions:
      - "files.include('apps/b*')"
    reviewers:
      users:
        - user-b
      << : *defaultReviews
```

This one just isn't valid at all (at least with pyyaml in Python). I don't have time to dig deeply at the moment, but I don't think you can merge lists like that with YAML anchors ([see this as one explanation](https://stackoverflow.com/questions/4948933/is-there-a-way-to-alias-anchor-an-array-in-yaml)). Is there a language/library you know of that parses this example correctly?
```yaml
securityTeam: &securityTeam
  - user-a
  - user-a2
  - user-a3

backendTeam: &backendTeam
  - user-b
  - user-b2
  - user-b3

groups:
  group-a:
    conditions:
      - "files.include('apps/a*')"
    reviewers:
      users:
        <<: *securityTeam
        <<: *backendTeam

  group-b:
    conditions:
      - "files.include('apps/b*')"
    reviewers:
      users:
        <<: *backendTeam
```
