### ISSUE TITLE
Labels not being removed

### ISSUE THREAD

**Issue by HPaulson** [pullapprove/support#134]
[In the PullApprove Labels Documentation](https://docs.pullapprove.com/config/labels/), the following is documented:

> When the status of a group changes, it will apply the label for the new status and **remove the label for the previous status.**

However, this seems to not be the case. Although the labels are added, they appear to never be removed. Example:

```yml
version: 3
notifications:
- when: pull_request.opened
  comment: |
    Pull request pending review from an Executive
- when: pullapprove.approved
  comment: "Pull request approved by Executive, Ready for merge"

groups:
  code:
    labels:
      approved: "approved"
      pending: "pending"
      rejected: "rejected"
    reviewers:
      teams:
      - executive
    reviews:
      required: 1  
      request: 1 
      request_order: given
``` 

In this case, the following occurs:
![image](https://user-images.githubusercontent.com/47159695/79349226-01803e80-7f04-11ea-97ec-28e8a198cb59.png)

As seen here, the `pending` role was removed manually, and PullApprove did not remove it when the status was changed as documented.

**Comment by davegaeddert** [comment]
Hey @C0braD3v, is that the full config you're using, or is there more? I know one of the things that has tripped people up is that the labels should be group-specific, otherwise you might get overlap/conflicts. For example, something like this could have both "pending" and "approved" labels at the same time if `one` is approved and `two` is pending.

```yaml
groups:
  one:
    labels:
      approved: "approved"
      pending: "pending"
      rejected: "rejected"
  two:
    labels:
      approved: "approved"
      pending: "pending"
      rejected: "rejected"
```
