### ISSUE TITLE
Labels config not working

### ISSUE THREAD

**Issue by bstanger** [pullapprove/support#136]
I'm trying to get labels applied to PRs that are pending a review from a specific group.  Here is what I have, based on looking at the [labels docs](https://docs.pullapprove.com/config/labels/):

```
version: 3
groups:
    consumer-shopex:
        reviewers:
            teams:
                - web-cx-shopex
        reviews:
            required: 1
            request: 0
        conditions:
            - "files.include('packages/app-consumer/src/Home/*')"
        labels:
            pending: "shopex needed"
```

But when I comment /pullapprove-test with this config, I always get the following error:

![Screen Shot 2020-06-12 at 12 12 15 PM](https://user-images.githubusercontent.com/6686485/84538127-fba99e00-aca5-11ea-9645-d72571188c95.png)

What am I doing wrong?
