### ISSUE TITLE
Allow list comprehension in condition statements

### ISSUE THREAD

**Issue by josephperrott** [pullapprove/support#140]
Is it possible to add support for list comprehensions in condition statements?

Example:
```yaml
fallback:
    <<: *defaults
    conditions:
      - *can-be-global-approved
      - len([g for g in groups.active if g not in ["required-minimum-review", "global-approvers", "global-docs-approvers"]]) == 0
```

Currently this fails on the `for` it appears.
```
error — Condition expression error: expected token ',', got 'for' in len([g for g in groups.active if g not in ["required-minimum-review", "global-approvers", "global-docs-approvers"]]) == 0
```

You can see the `/pullapprove-test` that exposed this error [here](https://app.pullapprove.com/report/?url=https%3A//storage.googleapis.com/pullapprove-storage/reports/b2d7c73c-e9b5-476e-a20b-d0530e47b56b.json%3FExpires%3D1597608348%26GoogleAccessId%3Dpullapprove-reporter%2540pullapprove.iam.gserviceaccount.com%26Signature%3DUB9adpf688kGkzEw72uSlr9T%252F0R0VnL%252FiN5WEeuWw%252FdciikhqT0Gf91RXfwo18GI01QwYBXWB6DwP5G7Bl%252F3Ioi6GZ7RiHsfdMAd20%252Fsh0gu15fHRIJTPQX8fjxdgbuut5McYLOA%252BQf7e5GM%252FcWKOVpQl1%252BSa7BaJ0AWBr%252BQFq1RysRJDJQmFnTg3VMleIGyBzSJtdJBppWsUbZpsMrf6em4LqzwYqzr5Xrw24Szrs5n6b2SWMUGJP6tQcz1L05qKyF4lq4Pd3thiZrl8xJmhu1wvS9BNkpgdSSJ5ndjC3NMmPHSYTJ3Jf%252FK1f0nZmc73b8hzeDW%252FDJs0SO56ht4xg%253D%253D&fingerprint=882bdb93d3ba9d74f44596828d9339bc)
