### ISSUE TITLE
reviews in order from different teams

### ISSUE THREAD

**Issue by akshatnair** [pullapprove/support#142]
Is this the right way to ensure that team1 reviews first and then team2 is asked for a review?

```
groups:
  # This is to ensure that team1 reviews first and then team2 is asked for a review
  ordered-code-review:
    reviews:
      required: 2
      request: 1
      request_order: given
    reviewers:
      teams:
        - team1
        - team2

```

**Comment by akshatnair** [comment]
this is for version: 3

**Comment by davegaeddert** [comment]
Hey @akshatnair! Can you say more about what you're trying to do? I'm guessing that this would be closer to what you're intending to do?

```yaml
groups:
  team1-review:
    reviews:
      required: 1
    reviewers:
      teams: [team1]
  team2-review:
    conditions: ["'team1-review' in groups.approved"]
    reviews:
      required: 1
    reviewers:
      teams: [team2]
```

Which basically says that 1 approval is required from each of the teams. And that team2 doesn't start until after team1 approves.

Let me know if that helps.
