### ISSUE TITLE
Reviewers group based on author

### ISSUE THREAD

**Issue by gzphreak** [pullapprove/support#148]
Hey, I'm trying to figure out how I would specify a different group of reviewers based on the PRs author. Is something like the config below possible?

```yaml
groups:
  team1:
    conditions:
      - "author in <team1.reviewers.users?>"
    reviewers:
      users:
        - user1
        - user2
        - user3
    reviews:
      required: 1
      request: 1
      request_order: shuffle
  team2:
    conditions:
      - "author in team2.reviewers.users"
    reviewers:
      users:
        - user4
        - user5
        - user6
    reviews:
      required: 1
      request: 1
      request_order: shuffle
```

**Comment by davegaeddert** [comment]
Hey @gzphreak -- good question. Right now, you'd need to manually make a list of usernames to do this:

```yaml
groups:
  team1:
    conditions:
      - "author in ['user1', 'user2', 'user3']"
```

Does that help in your case?

Are you specifically looking to assign a group if the author is also one of the reviewers for that same group?
