### ISSUE TITLE
Feature request: Per directory and per extension reviewer settings in the YAML config

### ISSUE THREAD

**Issue by d3ming** [pullapprove/support#19]
First, just wanna say great stuff on the yaml support! 

I'm wondering if you guys have plans to expand this further and specifically add support to customize directories of files / file type/extension. 

The user scenario is that we have a very large project and:
1. Certain directories may get different set of reviewers
2. Certain file types (i.e. php vs js) might require a different set of reviewers

Thanks!
Dong

**Comment by davegaeddert** [comment]
Good news, this is out in the wild and ready for some feedback! Although not officially documented yet, you can now add this to your .pullapprove.yml.

This works using Python's `fnmatch` (https://docs.python.org/2/library/fnmatch.html), which supports Unix shell-style wilcards.

A few simple examples:
- To match general file types: `"*.md"`
- To match all files in a directory: `"docs/*"`
- Combined: `"docs/*.md"`

``` yaml
reviewers:
    -
        name: normal-reviewers
        required: 2
        members:
            - x
            - y
    -
        name: php-reviewers
        required: 1
        members:
            - q
            - r
            - s
        conditions:
            files:  # if any of the following files are in PR, these people must review
                - "*.php"
                - "php-includes/*"
```
