### ISSUE TITLE
Branch-wise approval rules to support a gitflow like model

### ISSUE THREAD

**Issue by vaidik** [pullapprove/support#22]
It would be awesome if we can set different rules for different branches. Here is the use case. One of my teams here uses gitflow as the branching model. How this works is, we have a main `master` branch and a `staging` branch. staging branch is what is going to become master. All fixes and feature branches are merged into staging and finally when staging is stable, it is merged into master.

At times, there may be some hotfixes that are directly merged into master.

In case of pull requests against staging, we would want a very thorough review process and perhaps it gets lengthy too. In case of pull requests against master for hotfixes, we want this process to be really fast as something broke in production but the people who can merge the pull request have the be the senior most people of the team. So the rules change from branch to branch.

**Comment by davegaeddert** [comment]
@vaidik: so based on some other feature conversations going on (particularly with labels #27 and files #19), I'm wondering if a "conditions" section on a reviewer groups solves all of these problems.

So for your branches:

``` yaml
reviewers:
    -
        name: admins
        required: 1
        members:
            - vaidik
            - admintwo
            - adminthree
            - adminfour
        conditions:
            branches:  # if merging into one of these branches, these people must review
                - master
    -
        name: staging-reviewers
        required: 2
        members:
            - vaidik
            - usertwo
        conditions:
            branches:
                - staging
    -
        name: staging-security-reviewers
        required: 1
        members:
            - x
            - y
            - z
        conditions:
            branches:
                - staging
            labels:  # then you could use labels in a similar way -- "these people must review if one of these labels is present"
                - bug
                - hotfix
                - security-review-needed
            files:  # similar thing for file globs
                - docs/
                - **/*.md
```

Does that make sense? Thoughts?
