### ISSUE TITLE
Add ability to match GH teams to a teams property (apart from members property)

### ISSUE THREAD

**Issue by gabrieljoelc** [pullapprove/support#25]
It'd be nice if I could have "iOS", "Android", and "QA" GH teams and then just do:

``` yml
reviewers:
    -
        name: mobile
        required: 2
        teams:
              - iOS
              - Android
    -
        name: qa
        required: 1
```

Changed to @Lascorbe's [idea](https://github.com/pullapprove/support/issues/25#issuecomment-195702942) instead ⬆️

**Comment by mmacny** [comment]
+1!
Would be much easier for us to standardize user permissions this way. Plus, ensures that maintenance of the .yaml doesn't become a headache.

**Comment by davetapley** [comment]
+1

**Comment by bennettandrews** [comment]
+1

**Comment by rjmurillo** [comment]
:+1:  This would be helpful to us in coordinating permissions between applications. For example, we use PullApprove to show who needs to do a review, and Review Ninja to do the actual reviews.

**Comment by Lascorbe** [comment]
I think it'd better to have a new parameter like `teams` (apart from members). This way we have 3 main benefits:
- We can know exactly to what it's referring to (github teams)
- It won't clash with the current implementation (name)
- You can aggregate several teams to one "group" (like `Android` and `iOS` to the group named `Mobile`)

It'd look something like:

```
reviewers:
    -
        name: mobile
        required: 2
        teams:
              - iOS
              - Android
    -
        name: qa
        required: 1
```

**Comment by TomSadira777** [comment]
+1

**Comment by gabrieljoelc** [comment]
updated title and description to @Lascorbe's [idea](https://github.com/pullapprove/support/issues/25#issuecomment-195702942)

**Comment by davegaeddert** [comment]
This is now up and available if anybody wants to test it out!

We did go the route of adding a separate `teams` field, so you use it like @Lascorbe's example:

``` yaml
reviewers:
    -
        name: mobile
        required: 2
        teams:
              - ios  # use the slug
              - android
```

For existing repos, you'll want to manually trigger the syncing of teams -- just go to your org page (https://pullapprove.com/{your_organization}) or the repo settings page and click "sync" in the teams table.
![image](https://cloud.githubusercontent.com/assets/649496/14825693/850d33ce-0ba0-11e6-8b65-ae3270bfd9c9.png)

**Comment by davegaeddert** [comment]
We'll get some docs put up for this, but I forgot to mention that you'll need to use the **slug** for the team in your .pullapprove.yml (lowercase, hyphenated -- same as how it would show up in an @mention on GitHub).

**Comment by gabrieljoelc** [comment]
@davegaeddert I synched the teams at the organization level and added this to default template:

``` yml
reviewers:
  -
    name: dev
    required: 2
    teams:
      - dev
```

but got a `500`.
