### ISSUE TITLE
Impossible status scenario with "rejected"

### ISSUE THREAD

**Issue by davegaeddert** [pullapprove/support#29]
When using required == -1 (all reviewers must approve)

``` yaml
approve_by_comment: yes
reject_regex: ^Rejected
reviewers:
  required: -1
  members:
    - davegaeddert
    - pullapprover
```

<img width="646" alt="screen shot 2016-01-28 at 10 15 24 pm" src="https://cloud.githubusercontent.com/assets/649496/12667083/c425c0be-c60c-11e5-8ac3-75331d6c871c.png">
