### ISSUE TITLE
Allow top-level YAML options inside reviewer blocks

### ISSUE THREAD

**Issue by DavidDTA** [pullapprove/support#44]
Our workflow is generally Code -> Code review -> QA -> Merge.  Code review is done by an engineer, and QA is done by the developer who made the pull request and/or a dedicated QA person.

In the YAML file, several of the settings available only at the top level would be useful inside a `reviewers` block.

Our current YAML does not model the QA step, and looks like this:

```
approve_by_comment: true
approve_regex: ^[+]?LGTM
reject_regex: ^[-]LGTM
reset_on_push: true
author_approval: ignored
reviewers:
  members:
  - reviewer_a
  - reviewer_b
  - reviewer_c
  name: Code reviewers
  required: 1
  conditions:
    files:
      - "subdirectory/**"
```

We could specify the QA step in this way:

```
approve_by_comment: true
approve_regex: ^[+]?LGTM
reject_regex: ^[-]LGTM
reset_on_push: true
author_approval: ignored
reviewers:
  -
    members:
    - reviewer_a
    - reviewer_b
    - reviewer_c
    name: Code review
    required: 1
    conditions:
      files:
        - "subdirectory/**"
  -
    members:
    - reviewer_a
    - reviewer_b
    - reviewer_c
    - qa_a
    - qa_b
    name: QA
    required: 1
    conditions:
      files:
        - "subdirectory/**"
```

There are a few problems with this configuration, though:
Either `author_approval` is `ignored` and developers can't QA, or it is `default` and a developer's approval approves the code review as well.
The two different approvals must share the same `approve_regex` and `reject_regex`.
This also seems to apply to `approve_by_comment`, `reject_value`, `reset_on_push`, and `reset_on_reopen` as well, although it's not relevant to our workflow.
A better, but invalid config would look like this, where invalid configurations are highlighted:

```
approve_by_comment: true
reset_on_push: true
reviewers:
  -
    members:
    - reviewer_a
    - reviewer_b
    - reviewer_c
    name: Code review
    **approve_regex: ^[+]?LGTM**
    **reject_regex: ^[-]LGTM**
    **author_approval: ignored**
    required: 1
    conditions:
      files:
        - "subdirectory/**"
  -
    members:
    - reviewer_a
    - reviewer_b
    - reviewer_c
    - qa_a
    - qa_b
    name: QA
    **approve_regex: ^QA passed**
    **reject_regex: ^QA failed**
    required: 1
    conditions:
      files:
        - "subdirectory/**"
```

Thanks again for taking feedback,
David

**Comment by jodh-intel** [comment]
+1. We've hit this problem in a slightly different way. Our config is effectively:

```
reviewers:
  -
    name: code review
    teams:
      - the_entire_team
  -
    name: qa
    members:
      - team_member_1
      - team_member_2
```

Since `team_member_1` and `team_member_2` are members of `the_entire_team`, a "qa approval" approves the entire PR since `team_member_1` and `team_member_2`'s ack counts for both the "qa" and "code review" review groups.

The only ways around the current behavior seem to be:
- Ignore the pullapprove status and manually count the "acks" on a PR before actually merging.
  
  Ugh - the whole point of pullapprove is to allow the process to be automated.
- Remove `team_member_1` and `team_member_2` from `the_entire_team`.
  
  This isn't something we want to do as team membership isn't only used for pullapprove.
- Change the "code review" reviewer group to list every member who is _not_ in the "qa" reviewer group.
  
  This isn't ideal as the group is large and we don't want to have to maintain the list of members in the pullapprove config file (since it's already maintained via github).
- Create a special "QA user" who is not a member of `the_entire_team` and whose sole purpose is to perform approvals for the "qa" review group.
  
  This is not ideal either since that virtual user will require special privs that are currently maintained for the github group. There are also all the issues around shared users. However, this is probably the most pragmatic solution until a reviewer-specific `approve_regex` is supported by pullapprove.

If reviewer group-specific regex's were supported, our config could become:

```
# regex the applies to all reviewer groups that do not specify their own regex.
approve_regex: lgtm
reviewers:
  -
    name: code review
    teams:
      - the_entire_team
  -
    name: qa
    members:
      - team_member_1
      - team_member_2
    # XXX: regex's which only count as an ack/nack if the user is either team_member_1 or team_member_2
    approve_regex: qa-passed
    reject_regex: qa-failed
```
