### ISSUE TITLE
Add ability to add/remove labels automatically

### ISSUE THREAD

**Issue by Lascorbe** [pullapprove/support#46]
I'd be great if we could specify labels to put on a PR before and after approval. So, for example, imagine you always put the label `CR-Pending` when you want your colleagues to review your PR, and as soon as it's approved, you remove the label and the label `CR-Approved` is put there instead.

Here's how I think a `.pullapprove.yml` with this feature could look like:

```
approve_by_comment: true
approve_regex: '^:\+1:'
reject_regex: '^:\-1:'
reject_value: -1
reset_on_push: false
reset_on_reopened: true
author_approval: ignored
reviewers:
    -
        name: QA
        required: 1
        members:
            - qa_guy
        labels:
            pre_approval:
                - QA-Pending
                    color: bfd4f2
            post_approval:
                - QA-Approved ✓
                    color: 207de5
        conditions:
            labels:
                - QA-Review
    -
        name: Engineering
        required: 2
        members:
            - one_random_guy
            - other_random_guy
            - another_random_guy
        labels:
            pre_approval_labels:
                - CR-Pending
                    color: bfe5bf
            post_approval_labels:
                - CR-Approved ✓
                    color: 009800
            remove_after_approval: true   # if this is true, it'll remove the labels setted on the `pre_approval` section after the PR has been approved
```

What do you think?

**Comment by davegaeddert** [comment]
@Lascorbe thanks for putting this in here. We'll kick this around a little bit -- one thing I'm wondering is if there's a slightly different form this takes where you would be able to specify some actions that take place on `pre_approval` or `post_approval` (or other events). It might be adding/removing labels, sending webhooks, Slack integration, etc. Similar to what you've got but organized a little differently.

**Comment by davegaeddert** [comment]
Just to add to the labels conversation -- this has been asked about in relation to other features (`always_pending` might add a "wip" label, `signed_off_by` failing could add a "no-dco" label). Still not sure about this but we'll give some though to what this might look like a little more broadly.

**Comment by darnould** [comment]
An option to enable automatic labelling of pull requests to identify **which** groups still need to approve them would be extremely useful.

This would enable people to quickly identify and approve anything pending from their particular group, as it would allow the state of every PR to be visible on the overall PR listing page.  The current approach, which involves looking at each individual PR page periodically, is very slow and inefficient compared to this.

**Comment by cdeszaq** [comment]
Another use-case for this capability: Have labels for how _many_ reviews are still needed. I've seen a number of manual workflows that have multiple state transitions. Here's a description of one: https://github.com/yahoo/fili/blob/master/docs/contributing/code-review-pr-workflow.md#phases

**Comment by duglin** [comment]
To add to this... I'd really like it if PA could add a label based on how many LGTMs there are. For example, add a "LGTM1" label after the first.  Some people in our group want to run queries based on how many LGTMs there are on each PR.  Likewise, adding a label to indicate that its ready to be merged (meaning no conflicts or missing LGTMs) would be nice.

Not to put any pressure on anyone :-)   but I'd prefer to not have to code up a bot myself to do this.

**Comment by scherler** [comment]
To add our project specific needs and show another use case for this.

In our case all PR should be labeled "WIP" until there is a "green" build (in our case jenkins). Then the label should turn to "needs review" until 2 approval from push access team members. Then it turn to "ready to merge".

**Comment by mingshenggan** [comment]
+1

**Comment by kbucksch** [comment]
👍

**Comment by davegaeddert** [comment]
@kbucksch could you give a little more detail on how you'd use it? What kinds of labels, when, etc.

**Comment by kbucksch** [comment]
@davegaeddert sorry for not responding. Its a long time ago. Actually we changed the flow slightly therefore we do not have this need anymore. Sry for not beeing able to give more context.

**Comment by davegaeddert** [comment]
We finally started support for automatically managing labels in pullapprove v3! Better late than never?

```yaml
version: 3
groups:
  code:
    labels:
      # Each field is optional
      approved: "Code review approved"
      pending: "Code review pending"
      rejected: "Code review rejected"
```

https://docs.pullapprove.com/config/labels/

Can't believe it took this long to decide to take it on, but thanks to everybody here for the feedback.
