### ISSUE TITLE
Pull request is marked as rejected before reviewers approved it

### ISSUE THREAD

**Issue by ilyapuchka** [pullapprove/support#51]
The other problem we have now for some PRs is that new pull requests are marked as rejected or stay in a state where they are waiting for status information (but does not say that review is required).

Our setup is this:

``` yml
approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: true
author_approval: ignored
reviewers:
  members:
  - ilyapuchka
  - Nonnus
  - peterprokop
  name: default
  required: -1
```

It does not happen for all PR though.
Thanks in advance!
