### ISSUE TITLE
Feature idea: treat templates like mixins instead of overriding

### ISSUE THREAD

**Issue by gabrieljoelc** [pullapprove/support#61]
If i had these two templates:

``` yml
# default template

approve_by_comment: true
approve_regex: '^(:shipit:)'
author_approval: ignored
reject_regex: ^Rejected
reject_value: -99
reviewers:
  -
    name: dev
    required: 2
    teams:
      - dev

# qa template

reviewers:
  -
    name: qa
    required: 1
    teams:
      - qa
```

It would be cool if I could just do:

``` yml
# .pullapprove.yml

extends default
extends qa
```

And it would just merge the configuration.

Relates to #34

**Comment by gabrieljoelc** [comment]
@davegaeddert currently, if i had 

``` yml
# default template

reviewers:
  -
    name: dev
    required: 2
    teams:
      - dev
```

would the following merge the `reviewers` configuration (the [docs](http://docs.pullapprove.com/yaml/extends/) don't say)?

``` yml
# .pullapprove.yml

extends default
reviewers:
  -
    name: oneoff_group
    required: 1
    members:
      - captainjack
```
