### ISSUE TITLE
Block Work In Progress by regex on the title on the pull request

### ISSUE THREAD

**Issue by kobymeir** [pullapprove/support#62]
Allow to block pull requests based on their title match (or not) a regex, for my scenario i want to block pull requests that are labeled with "**WIP** new feature" or "**[WIP]** new feature" "**Not finished**: new feature"

YAML example:
`title_block_regex: '^(WIP|[WIP]|Not finished)'`

**Comment by davegaeddert** [comment]
@kobymeir in your mind would this put the status check in the failed/rejected state or pending? I'm thinking "pending", but wanted to get your feedback. I'm also thinking that it may be worth broadening this a little to have similar functionality for labels...

**Comment by kobymeir** [comment]
@davegaeddert I think that "pending" is the better approach
I personally don't use labeling, but sounds reasonable to me.

**Comment by davegaeddert** [comment]
@kobymeir agreed. This is up and functional if you want to give it a test -- I'd appreciate any feedback. We went with a more generic `always_pending` setting (could later add `always_rejected`, maybe `always_approved` as well). Available at the root level of your yaml, looks like this:

``` yaml
always_pending:
    title_regex: '^(WIP|wip)'
    labels:
        - wip
```

**Comment by kobymeir** [comment]
@davegaeddert :+1: i gave it a try and it's excellent , a minor improvement might be a way to control the status message that is shown `Title meets 'always_pending' conditions` to a custom message `cannot merge work in progress` or whatever the comes to mind

**Comment by davegaeddert** [comment]
@kobymeir I agree, and figured that was worth adding right away so it's as useful as possible. So now there's also an `explanation` field:

``` yaml
always_pending:
    title_regex: '^(WIP|wip)'
    labels:
        - wip
    explanation: 'Cannot merge work in progress'
```

Let me know what you think.
