### ISSUE TITLE
Branches conditions support for negation (i.e. `!master`)

### ISSUE THREAD

**Issue by davegaeddert** [pullapprove/support#67]
Add support for using `!` in the branches conditions (similar to #52).

``` yaml
conditions:
  branches:
    - !master
    - !develop
```

(would mean that these people need to review any PR's not merging into master or develop)
