### ISSUE TITLE
Branches conditions support for specific base...head

### ISSUE THREAD

**Issue by davegaeddert** [pullapprove/support#68]
Add the ability to specify both the name of the target branch and the name of the PR branch.

``` yaml
conditions:
  branches:
    - master...develop
    - develop...master
```

(would mean that merging between master and develop needs to be reviewed)

These could also be negated - #67
