### ISSUE TITLE
always_pending does not respect label on PR creation

### ISSUE THREAD

**Issue by jaymecd** [pullapprove/support#84]
File `.pullapprove.yml` has following settings:

```
...
always_pending:
  title_regex: '(WIP|wip)'
  labels:
    - "WIP"
    - "Don't Merge"
  explanation: "NOTE: Work in progress / PR is frozen"
...
```

When new PR is created with label 'WIP', status says: Approval required by 2 of: ...
If I remove `WIP` label and and then I add it back, status says: NOTE: Work in progress / PR is frozen
